title: annema.me
email: kp@annema.me
description: >
  Occassional writings about programming and software.
baseurl: "/"
twitter_username: klaaspieter
github_username: klaaspieter

markdown: kramdown
strict_front_matter: true
theme: minima
remote_theme: broccolini/swiss
theme_color: black
plugins:
  - jekyll-feed
