title: annema.me
email: kp@annema.me
description: >
  Occassional writings about programming and software.
baseurl: ""
url: https://annema.me
enforce_ssl: annema.me

social_username: klaaspieter
github_username: klaaspieter
github_repo: annemame

markdown: kramdown
strict_front_matter: true
remote_theme: broccolini/swiss
theme_color: black
plugins:
  - jekyll-feed
