server {
    listen 80;
    root /usr/share/nginx/html;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Content-Security-Policy "default-src 'self'; base-uri 'self'; form-action 'none'; frame-ancestors 'self';" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /flavor.js {
      resolver 127.0.0.11 valid=30s;
      set $umami annemame-umami;
      proxy_pass http://$umami:3000/script.js;
      proxy_set_header Host stats.annema.me;
      proxy_buffering on;
    }

    location = /api/send {
      resolver 127.0.0.11 valid=30s;
      set $umami annemame-umami;
      proxy_pass http://$umami:3000/api/send;
      proxy_set_header Host stats.annema.me;
      proxy_buffering on;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
    }
}
