service: annemame

# Name of the container image.
image: kp/annemame

# Deploy to these servers.
servers:
  web:
    - 91.99.116.152

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  hosts:
    - annema.me
    - annema.nyc
    - imme.nyc

# Credentials for your image host.
registry:
  server: registry.unskim.eu
  username: kp
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
