service: annemame

# Name of the container image.
image: kp/annemame

# Deploy to these servers.
servers:
  web:
    - annema.me

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  hosts:
    - annema.me
    - www.annema.me
    - annema.nyc
    - www.annema.nyc
    - imme.nyc
    - www.imme.nyc

# Credentials for your image host.
registry:
  server: registry.unskim.eu
  username: kp
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

accessories:
  umami-db:
    image: postgres:17
    host: annema.me
    port: "127.0.0.1:5433:5432"
    env:
      clear:
        POSTGRES_USER: umami
        POSTGRES_DB: umami
      secret:
        - POSTGRES_PASSWORD
    directories:
      - umami-db-data:/var/lib/postgresql/data

  umami:
    image: docker.umami.is/umami-software/umami:3.0.3
    host: annema.me
    env:
      secret:
        - DATABASE_URL

aliases:
  add-umami-to-proxy: |
    server exec docker exec kamal-proxy kamal-proxy deploy umami
    --target "annemame-umami:3000"
    --host "stats.annema.me"
    --tls
    --health-check-path "/api/heartbeat"
    --buffer-requests
    --buffer-responses
